### PR TITLE
Libnetcdf and pmw dependency

### LINKED ISSUE #6: Molfile plugins not compiled in
- [X ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: .gro files are not supported, probably because the molfile plugins are not compiled in, as they need libnetcdf. A "{{ pin_compatible('libnetcdf', max_pin='x.x') }}" in the dependencies should do the trick (I do the same in my pymol-open-source build in the "awacha" anaconda channel). The pinning is needed because the so version changed recently.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ca-certificates           2021.1.19            h06a4308_0  
certifi                   2020.12.5        py39h06a4308_0  
dbus                      1.13.18              hb2f20db_0  
expat                     2.2.10               he6710b0_2  
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
glew                      2.1.0                h9c3ff4c_2    conda-forge
glib                      2.66.1               h92f7085_0  
glm                       0.9.9.4              hc9558a2_0    conda-forge
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
icu                       58.2                 he6710b0_3  
jpeg                      9b                   h024ee3a_2  
ld_impl_linux-64          2.33.1               h53a641e_7  
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libglu                    9.0.0                hf484d3e_1  
libgomp                   9.3.0               h2828fa1_18    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
ncurses                   6.2                  he6710b0_1  
numpy                     1.20.1           py39hdbf815f_0    conda-forge
openssl                   1.1.1i               h27cfd23_0  
pcre                      8.44                 he6710b0_0  
pip                       20.3.3           py39h06a4308_0  
pymol-open-source         2.4.0            py39h20a8f2e_3    conda-forge
pyqt                      5.9.2            py39h2531618_6  
python                    3.9.1                hdb3f193_2  
python_abi                3.9                      1_cp39    conda-forge
qt                        5.9.7                h5867ecd_1  
readline                  8.1                  h27cfd23_0  
setuptools                52.0.0           py39h06a4308_0  
sip                       4.19.13          py39h2531618_0  
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
tzdata                    2020f                h52ac0ba_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h27cfd23_1007  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : pymol
    active env location : /opt/miniconda3/envs/pymol
            shell level : 1
       user config file : /home/wachaandras/.condarc
 populated config files : /home/wachaandras/.condarc
          conda version : 4.9.2
    conda-build version : 3.21.4
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.33=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/awacha/linux-64
                          https://conda.anaconda.org/awacha/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://levinthal:paradox@conda.graylab.jhu.edu/linux-64
                          https://levinthal:paradox@conda.graylab.jhu.edu/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/wachaandras/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /home/wachaandras/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.5 Linux/5.10.15-arch1-1 arch/rolling glibc/2.33
                UID:GID : 1000000:1000
             netrc file : None
           offline mode : False

```
</details>

### PR DESCRIPTION
**Pull request by awacha**
Checklist
* [ X ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ X ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ X ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ X ] Ensured the license file is being packaged.

Closes #6 

Added dependency of libnetcdf. Was a bit tricky because between 4.7.3 and 4.7.4 the .so version changed from 15 to 18 (libnetcdf.so.15 -> libnetcdf.so.18), so a 'x.x.x' pinning was needed. Pmw is also added to ensure working of legacy plug-ins, e.g. abps.

### CODE REVIEW

**Comment by padix-key** [comment]
Hi, thank you for supporting the recipe! If have a question regarding the pinning: As I understand `pin_compatible` gives a version range for `run` that is compatible with the version of the package used in `host`. Therefore, I understand what the pinning does in `run`, but why do you set  `{{ pin_compatible("libnetcdf", max_pin="x.x.x", min_pin="x.x.x")}}` is also in `host`, instead of simply `libnetcdf = 4.7.4`?

**Comment by awacha** [comment]
Hi,

thank you for your comment, I'm happy to help. You are right, I did not understand the subtle differences between host, build and run environments. Now I see, thank you. Should I update the meta.yaml file as you suggest?

Talking about the version: in principle, I wouldn't restrict the package to any given libnetcdf version needlessly: any recent version should be OK. Probably building against the most recent 2-3 versions (aka a build matrix) would make things easier when one wants to install this package and other ones depending on libnetcdf. But maybe this is an overkill?

**Comment by padix-key** [comment]
To add different `libnetcdf` versions to the build matrix seems a little bit too much in my opinion, especially as this could consequently also be done for `numpy`. I suggest that we set `libnetcdf =4.7.4` in `host`, so that we can use an unrestricted `{{ pin_compatible("libnetcdf") }}` in `run` as I expect that the binary compatibility (hopefully) will not change any time soon again. In this case all `libnetcdf` versions `>= 4.7.4, < 5.0.0` would be allowed as runtime dependency. Do you think this is a viable solution?

Another good thing would be a test, whether the VMD-Plugins work. Do you know a PyMOL command that uses the `libnetcdf` dependency, other than loading a structure file? The `conda-forge` maintainers would like to keep the feedstocks small, so including larger file in the feedstock, e.g. a structure file, is discouraged.

My third question addresses `pmw`: Did you test, if `pmw` a dependency at compile time, or merely a runtime dependency? As I have no experience with these: Are there still widgets in PyMOL 2 that use `pmw`, because the [PyMOL installation instructions](https://github.com/schrodinger/pymol-open-source/blob/master/INSTALL), state that it is used for legacy GUI plugins?

**Comment by awacha** [comment]
Hi @padix-key,
thanks for your comments.

1. According to your suggestion, I fixed `libnetcdf=4.7.4` in the `build` section and put a more relaxed `{{ pin_compatible("libnetcdf") }}` macro in the `run` section.
2. Added a test for the molfile plug-ins. The test data is the model of an unterminated alanine tripeptide made by the `fab AAA` PyMOL command and converted to GRO and G96 format with [GROMACS 2020.3](https://manual.gromacs.org/2020.3). The data is short (only 30 atoms each format) and included in-line in `test.py`, so hopefully the `conda-forge` maintainers won't complain about large files cluttering the tree.
3. Now the `pmw` dependency is only present in the `run` section. I have checked, PyMOL recognizes it and offers legacy plug-ins in the `Plugin` menu. Although the upstream-supplied ABPS plug-in is broken (code not updated for Python 3, e.g. `string` module functions like `string.strip()` are still present), there are several third party plug-ins still using the tkinter-based GUI. I think it would be polite if we supported those until the developers of PyMOL explicitly deprecate the old GUI. 
4. A cosmetic edit in `test.py`: now the `tempfile.TemporaryDirectory` context manager is used instead of `tempfile.gettempdir()`. This way a dedicated temporary directory is created (e.g. `/tmp/locdqb1d`) instead just putting the files under `/tmp`. This avoids file name clashes (e.g. if another instance of this script is running paralelly on the same machine) with a plus that the temporary directory is automatically removed when the context manager `__exit__()`s.

I hope this helps, please let me know if you have other comments.

**Comment by padix-key** [comment]
The PR looks ready to merge for me now.

If you like, you may also add yourself to the `recipe-maintainers`.

**Comment by awacha** [comment]
Thanks. I did so. If you like then, you may merge the PR and close the corresponding issue #6.

**Pull request merged**
